name: Continuous Integration
on:
  push:
    branches:
      - "main"
      - "release/*"
    paths-ignore:
    - 'docs/**'
  pull_request:
    paths-ignore:
    - 'docs/**'

env:
  TreatWarningsAsErrors: true
  ContinuousIntegrationBuild: true
  PublishRepositoryUrl: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [debug, release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          global-json-file: global.json

      # Only the .NET runtime is needed. But setup-dotnet does not support installing only runtimes.
      # https://github.com/actions/setup-dotnet/pull/678
      # So, install whole SDK for now.
      - name: Setup .NET 6
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }} -bl:artifacts/log/build.binlog

      - name: Test
        run: dotnet test --no-build --no-progress --configuration ${{ matrix.configuration }} -bl:artifacts/log/test.binlog

      - name: Pack
        run: dotnet pack --no-build --configuration ${{ matrix.configuration }} -bl:artifacts/log/pack.binlog

      - name: Upload NuGet Packages
        if: matrix.configuration == 'release' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: nuget-packages-${{ matrix.os }}_${{ matrix.configuration }}
          path: ./artifacts/package/**/*
          if-no-files-found: error

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ matrix.os }}_${{ matrix.configuration }}
          path: |
            ./artifacts/bin/**/*
            ./artifacts/log/**/*
          if-no-files-found: error
